- hosts: ismail
  vars_prompt:
   - name: "version skype"
     prompt: "quel version Skype voulez-vous installer?"
     private: no
   - name: "url"
     prompt: "quel est l'URL pour telecharger skype?"
     private: no
  roles:
    - role: skype-install
